### ISSUE TITLE
Digest objects using only the digest (not the namespaces and type prefix)

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-python#27]
Based on gks leads meeting after VR, we agreed to digest nested objects using only their digests (without the ga4gh and type prefixes) in order to insulate computed digests from possible changes in the id structure.

**Comment by reece** [comment]
Example:

```python
>>> interval = ga4gh.vr.models.Interval(start=10,end=11)                                                                                                                                                     
>>> location = ga4gh.vr.models.Location(sequence_id="ga4gh:SQ/0123abcd", interval=interval)                                                                                                                  
>>> state = ga4gh.vr.models.SequenceState(sequence="C")                                                                                                                                                      
>>> allele = ga4gh.vr.models.Allele(location=location, state=state)                                                                                                                                          
>>> serialize(allele)                                                                                                                                                                                        
b'{"location":"lGBsEujtdjKPTxBMCPAeGArLgNEuPN99","state":{"sequence":"C","type":"SequenceState"},"type":"Allele"}'
```

**Comment by larrybabb** [comment]
@reece Quick question - and you possibly have this covered, but...

Is the new change checking that the value of the sub-digest fields is conformant to the computed digest specifications for length and character-set?  I would think that the "ga4gh:SQ/0123abcd" sequence_id in the location object above would fail since it is not the correct length according to spec.

If we are going to create the rule that our digests must only consume ids that are our digests then we should identify values that are incorrect, with the information available.

**Comment by reece** [comment]
I don't currently check the length and char set of the digest. I don't have a strong feeling either way about this. I'll implement.

**Comment by reece** [comment]
This actually needs to be checked in a couple of places. Deferring until after spec release.
