### ISSUE TITLE
Makefile xargs -r argument not supported on macosx

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-python#39]
There are three xargs commands in the "clean" steps at the end of the Makefile that don't work on macosx.  The xargs command in BSD does not support the -r (--no-run-if-empty) option. 

```
...
#= CLEANUP
...
clean:
	find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0r rm
...
cleaner: clean
	rm ...
	find . \( -name \*.pyc -o -name \*.orig -o -name \*.rej \) -print0 | xargs -0r rm
	find . -name __pycache__ -print0 | **xargs -0r rm -fr**
```

If the -r option is dropped it works fine since the BSD version does not run the command when empty. 

I'm not sure of the best workaround, but macosx users are likely to hit this causing mild frustration and delay in getting started for some.

**Comment by reece** [comment]
Here are workarounds for Mac OS:
https://stackoverflow.com/questions/17402345/ignore-empty-results-for-xargs-in-mac-os-x

Options:
* Drop `-r`... but this means that running make clean twice will fail (because `rm` will get no arguments)
* Tell Mac OS folks that they need to use a Linux virtual machine. (This also provides a workaround to separate annoyances with docker on Macs.)
* Implement the heinous workarounds in the stackoverflow answers.
* Add `-r` when not on Mac OS only. Downside: Mac users will get an error when cleaning a clean directory.

The last of these is easy and has no downsides on the primary target environment (linux). Let's do that.

**Comment by reece** [comment]
Here's the hacky testing on my machine:

```
$ make -n clean
find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0r rm

$ make -n clean UNAME=Darwin
find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0 rm
```

@larrybabb Please pull master and try `make clean`. It will fail if your directory is already clean, but should otherwise work.


P.S. Here's the test of the failure:
```
# first time 'round works:
snafu$ make clean
find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0r rm

# With -r flag on linux, second time works too
snafu$ make clean
find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0r rm

# But, without -r, cleaning a clean directory results in an error that I assume will be similar on mac OS:
snafu$ make clean UNAME=Darwin
find . \( -name \*~ -o -name \*.bak \) -print0 | xargs -0 rm
rm: missing operand
Try 'rm --help' for more information.
make: *** [Makefile:109: clean] Error 123


```
